// src/components/layout/navbar.tsx
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
} from "@/components/ui/navigation-menu";
import { Book, Newspaper, LinkedinIcon, GithubIcon } from "lucide-react";

const socialLinks = [
  {
    href: "https://github.com/cem-sirin",
    label: "GitHub",
    icon: GithubIcon,
    className: "hover:text-gray-700",
    ariaLabel: "GitHub",
  },
  {
    href: "https://linkedin.com/in/cem-sirin",
    label: "LinkedIn",
    icon: LinkedinIcon,
    className: "hover:text-blue-700",
    ariaLabel: "LinkedIn",
  },
];

function Navbar() {
  // Navigation links array with icon components
  const navigationLinks = [
    { href: "/", label: "CV", icon: Book },
    { href: "/blog", label: "Blog", icon: Newspaper },
  ];

  return (
    <header className="border-b mb-8 sticky top-0 z-50 bg-background/50 backdrop-blur">
      <div className="flex h-16 items-center justify-between gap-4">
        {/* Left: Name */}
        <div className="flex flex-1 items-center">
          <span className="font-bold text-lg text-primary">Cem Şirin</span>
        </div>
        {/* Center: Navigation */}
        <NavigationMenu>
          <NavigationMenuList className="gap-2">
            {navigationLinks.map((link, idx) => {
              const Icon = link.icon;
              return (
                <NavigationMenuItem key={idx}>
                  <NavigationMenuLink
                    href={link.href}
                    className="flex flex-row items-center gap-2 font-medium text-foreground hover:text-primary"
                  >
                    <Icon
                      size={16}
                      className="text-muted-foreground/80"
                      aria-hidden="true"
                    />
                    <span>{link.label}</span>
                  </NavigationMenuLink>
                </NavigationMenuItem>
              );
            })}
          </NavigationMenuList>
        </NavigationMenu>
        {/* Right: Social Icons */}
        <div className="flex flex-1 items-center justify-end gap-4">
          {socialLinks.map((link, idx) => {
            const Icon = link.icon;
            return (
              <a
                key={idx}
                href={link.href}
                target="_blank"
                rel="noopener noreferrer"
                aria-label={link.ariaLabel}
                className={link.className}
              >
                <Icon size={20} />
              </a>
            );
          })}
        </div>
      </div>
    </header>
  );
}

export default Navbar;

// src/lib/components/navbar.svelte
<script lang="ts">
	import {
		NavigationMenuRoot,
		NavigationMenuList,
		NavigationMenuItem,
		NavigationMenuLink
	} from '$lib/components/ui/navigation-menu';
	import PixelIcon from '$lib/components/pixel-icon.svelte';
	import { Button } from '$lib/components/ui/button';
	import ThemeToggle from '$lib/components/theme-toggle.svelte';

	const navLinks = [
		{ href: '/', icon: 'file-text', text: 'CV' },
		{ href: '/blog', icon: 'book', text: 'Blog' }
	];
</script>

<div class="fixed top-0 z-10 flex w-full items-center justify-center border-b p-4 backdrop-blur-sm">
	<!-- Left: Name -->
	<div class="absolute left-4 text-xl font-semibold">./cem/şirin</div>

	<!-- Middle: Navigation -->
	<NavigationMenuRoot>
		<NavigationMenuList>
			{#each navLinks as link}
				<NavigationMenuItem>
					<NavigationMenuLink href={link.href}>
						<div class="flex items-center gap-2">
							<PixelIcon name={link.icon} size="16px" />
							{link.text}
						</div>
					</NavigationMenuLink>
				</NavigationMenuItem>
			{/each}
		</NavigationMenuList>
	</NavigationMenuRoot>

	<!-- Right: Social Icons and Theme Toggle -->
	<div class="absolute right-4 flex items-center gap-2">
		<a href="https://www.linkedin.com/in/cem-sirin/" target="_blank" rel="noopener noreferrer">
			<Button variant="ghost" size="sm">
				<PixelIcon name="linkedin" size="16px" />
			</Button>
		</a>
		<a href="https://github.com/cem-sirin" target="_blank" rel="noopener noreferrer">
			<Button variant="ghost" size="sm">
				<PixelIcon name="github" size="16px" />
			</Button>
		</a>
		<ThemeToggle />
	</div>
</div>
